/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication6;

import java.awt.Component;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.Multipart;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeBodyPart;
import javax.mail.internet.MimeMessage;
import javax.mail.internet.MimeMultipart;
import javax.swing.JOptionPane;

/**
 *
 * @author ypila
 */
public class ForgotPassword extends javax.swing.JFrame {

    /**
     * Creates new form ForgotPassword
     */
    public ForgotPassword() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        fp_email = new javax.swing.JTextField();
        fp_send = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Enter your EMAIL-ID :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 112, -1, -1));
        getContentPane().add(fp_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 142, 248, -1));

        fp_send.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        fp_send.setText("Done!!");
        fp_send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fp_sendActionPerformed(evt);
            }
        });
        getContentPane().add(fp_send, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, -1, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 100, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication6/newpackage/banner_forgot.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 94));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication6/newpackage/banner-password.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 218, 740, 84));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fp_sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fp_sendActionPerformed
        // TODO add your handling code here:
        String femail= fp_email.getText();
          Component frame = null;
          String password ="";
         String subject = "Password Recovered";
         String messg = "Your password Recovered is :";
        String Email_reg= "^[_A-Za-z0-9-]+(\\.[_A-Za-z0-9-]+)*@[A-Za-z0-9]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$";// - See more at: http://www.java2novice.com/java-collections-and-util/regex/valid-email-address/#sthash.rjZeh4wS.dpuf
      
        
         
        
        
        
        
        Boolean b =femail.matches(Email_reg);
      if("".equals(femail))
              {
                  
                  JOptionPane.showMessageDialog(frame,"Enter email");
                  
             }
      else if(b==false)
                  {
                   JOptionPane.showMessageDialog(frame,"Enter Correct email");
                  }
       else
      {
          //Connection c = null;
       Statement stmt = null;
       try {
            String url = "jdbc:mysql://127.0.0.1:3306/";
            String dbName = "antiphishing";
            String driver = "com.mysql.jdbc.Driver";
            String userName = "root";
            String dbpassword = "";
            Class.forName(driver);
            // Connection set up with database named as user
            Connection c = DriverManager.getConnection(url+dbName,userName,dbpassword);
            c.setAutoCommit(false);
            System.out.println("Opened database successfully");

            stmt = c.createStatement();
                 ResultSet rs= stmt.executeQuery( "SELECT password FROM register WHERE email='"+femail+"';");
            
               
                if(rs.next())
                {
                       password = rs.getString("password");
                 
                }  } catch (SQLException ex) {
                Logger.getLogger(ForgotPassword.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
            Logger.getLogger(ForgotPassword.class.getName()).log(Level.SEVERE, null, ex);
        }
       messg =messg+"  "+ password;
          Properties props = new Properties();
props.put("mail.smtp.host","smtp.gmail.com");
props.put("mail.smtp.socketFactory.port","465");
props.put("mail.smtp.socketFactory.class","javax.net.ssl.SSLSocketFactory");
props.put("mail.smtp.auth","true");
props.put("mail.smtp.port","465");
Session session= Session.getDefaultInstance(props,new javax.mail.Authenticator(){
@Override
public PasswordAuthentication getPasswordAuthentication() {
 return new PasswordAuthentication("antiphishing544@gmail.com","@ntiPhishing"); //// PLEASE CHANGE THE EMAIL ID AND PASSWord
            }});    
try{
Message message = new MimeMessage(session);
         
                message.setFrom(new InternetAddress("antiphishing544@gmail.com"));//Enter EMAILID AGAIN
            
                message.setRecipients(Message.RecipientType.TO,InternetAddress.parse(femail));
           
           
                message.setSubject(subject);
            

MimeBodyPart mbp = new MimeBodyPart();
               mbp.setText(messg);
               Multipart mp = new MimeMultipart();
               mp.addBodyPart(mbp);
               message.setContent(mp);


Transport.send(message);
            
          JOptionPane.showMessageDialog(frame,"Check your Mail");

}
catch (MessagingException ex) {
                Logger.getLogger(ForgotPassword.class.getName()).log(Level.SEVERE, null, ex);
            }
      }
              
    }//GEN-LAST:event_fp_sendActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Login l = new Login();
                 l.setVisible(true);
                 setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForgotPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fp_email;
    private javax.swing.JButton fp_send;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
