/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication6;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javaapplication6.*;
import static javaapplication6.MailFetch.*;

/**
 *
 * @author ypila
 */
public class maildisplay extends javax.swing.JFrame {
    
    
    String url = "jdbc:mysql://127.0.0.1:3306/";
            String dbName = "antiphishing";
            String driver = "com.mysql.jdbc.Driver";
            String userName = "root";
            String dbpassword = "";

    private String selected;

    /**
     * Creates new form maildisplay
     */
    public maildisplay() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        mr_from = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        mr_subject = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        md_edp = new javax.swing.JEditorPane();
        mr_html = new javax.swing.JButton();
        md_date = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        md_type = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication6/newpackage/global_logo_.png"))); // NOI18N

        jLabel2.setText("FROM:");

        mr_from.setEditable(false);
        mr_from.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mr_fromActionPerformed(evt);
            }
        });

        jLabel3.setText("Subject:");

        mr_subject.setEditable(false);
        mr_subject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mr_subjectActionPerformed(evt);
            }
        });

        jLabel4.setText("message");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        md_edp.setEditable(false);
        md_edp.setContentType("text/html");
        jScrollPane2.setViewportView(md_edp);

        mr_html.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        mr_html.setText("HTML");
        mr_html.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mr_htmlActionPerformed(evt);
            }
        });

        md_date.setEditable(false);

        jLabel5.setText("DATE:");

        jLabel6.setText("Content Type:");

        md_type.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(mr_html)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel4)))
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(mr_subject)
                            .addComponent(md_date)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(mr_from, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 94, Short.MAX_VALUE))
                            .addComponent(md_type))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(mr_from, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(mr_subject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(md_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(md_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(mr_html)
                        .addGap(25, 25, 25))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                        .addContainerGap())))
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mr_fromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mr_fromActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mr_fromActionPerformed

    private void mr_subjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mr_subjectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mr_subjectActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here :
            int i = 0;
            int j = 1;
            if(caller == "newclass")
            new NewClass();
            else
            new NewClass1();    
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(maildisplay.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(maildisplay.class.getName()).log(Level.SEVERE, null, ex);
        }
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void mr_htmlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mr_htmlActionPerformed
        // TODO add your handling code here:
        new HtmlContent(sel,caller);
    }//GEN-LAST:event_mr_htmlActionPerformed

    /**
     * @param args the command line 
     * 
     * 
     */
    void display(int selected,String newclass)
    {
        sel = selected;
        caller = newclass;
        Connection c = null;
       Statement stmt = null;
       try {
           
            Class.forName(driver);
            c = DriverManager.getConnection(url+dbName,userName,dbpassword);
            c.setAutoCommit(false);
            System.out.println("Opened database successfully");
            stmt=c.createStatement();
       
            int h = 2;
            System.out.println(selected);
         stmt = c.createStatement();
                 ResultSet rs= stmt.executeQuery( "SELECT * FROM mail WHERE mid='"+(selected)+"';");
                 //String s ="<html> <body> hrllo </body> </html>";
                  
                  //md_edp.setContentType("text/html");
    //md_edp.setEditable(false);
   /*String sq= (rs.getString("content"));
                    if(sq.contains("text/html"))
                    {
                        mr_html.setVisible(true);
                    }
                    else
                    {
                        mr_html.setVisible(false);
                    }*/
                     //v =msgs.elementAt(selected);
   System.out.println(mail[selected]);
                 while(rs.next())
                 {
                     mr_from.setText(rs.getString("fr"));
                     mr_subject.setText(rs.getString("subject"));
                     String sq= (rs.getString("content"));
                     md_type.setText(rs.getString("content"));
                     md_date.setText(rs.getString("date"));
                    if(sq.contains("multipart"))
                    {
                        mr_html.setVisible(true);
                    }
                    else
                    {
                        mr_html.setVisible(false);
                    }
                    md_edp.setText(mail[selected]);
                 }
    }
       catch(Exception e)
       {
           
       }
    }
    
    
    void display1(int selected, String newclass1)
    {   
        sel = selected;
        caller = newclass1;
        Connection c = null;
       Statement stmt = null;
       try {
       Class.forName(driver);
            c = DriverManager.getConnection(url+dbName,userName,dbpassword);
            c.setAutoCommit(false);
            System.out.println("Opened database successfully");
            stmt=c.createStatement();
         System.out.println("Opened database successfully");
            int h = 2;
            System.out.println(selected);
         stmt = c.createStatement();
                 ResultSet rs= stmt.executeQuery( "SELECT * FROM PHISH WHERE pid='"+(selected)+"';");
                 //String s ="<html> <body> hrllo </body> </html>";
                  
                  //md_edp.setContentType("text/html");
    //md_edp.setEditable(false);
   /*String sq= (rs.getString("content"));
                    if(sq.contains("text/html"))
                    {
                        mr_html.setVisible(true);
                    }
                    else
                    {
                        mr_html.setVisible(false);
                    }*/
                     //v =msgs.elementAt(selected);
   System.out.println(pmail[selected]);
                 while(rs.next())
                 {
                     mr_from.setText(rs.getString("fr"));
                     mr_subject.setText(rs.getString("subject"));
                     String sq= (rs.getString("content"));
                     md_type.setText(rs.getString("content"));
                     md_date.setText(rs.getString("date"));
                    if(sq.contains("multipart"))
                    {
                        mr_html.setVisible(true);
                    }
                    else
                    {
                        mr_html.setVisible(false);
                    }
                    md_edp.setText(pmail[selected]);
                 }
    }
       catch(Exception e)
       {
           
       }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(maildisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(maildisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(maildisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(maildisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                maildisplay md =new maildisplay();
               // md.display();
                md.setVisible(true);
            }
        });
    }
 String msgg = "";
 String caller = "";
 Vector v = new Vector();
 int sel = 0;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField md_date;
    private javax.swing.JEditorPane md_edp;
    private javax.swing.JTextField md_type;
    private javax.swing.JTextField mr_from;
    private javax.swing.JButton mr_html;
    private javax.swing.JTextField mr_subject;
    // End of variables declaration//GEN-END:variables
}
