/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication6;

import java.awt.Component;
import java.awt.HeadlessException;
import java.io.File;
import java.io.IOException;
import static java.lang.ProcessBuilder.Redirect.from;
import java.util.Properties;
import javax.mail.Authenticator;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.internet.AddressException;
import javax.swing.JOptionPane;
import javax.mail.*;                                                                                                                
import javax.mail.internet.*;                                                                                                    
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.activation.DataHandler;
import javax.activation.DataSource;
import javax.activation.FileDataSource;
import javax.swing.JFileChooser;
import javaapplication6.*;
//import sendmail.Sendmail;

/**
 *
 * @author ypila
 */
public class mailsend extends javax.swing.JFrame {

    /**
     * Creates new form mailsend
     */
    public mailsend(String userid, String pass) {
        userid1 =userid;
        pass1 = pass;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        ms_label_to = new javax.swing.JLabel();
        ms_label_subject = new javax.swing.JLabel();
        ms_sendid = new javax.swing.JTextField();
        ms_subject = new javax.swing.JTextField();
        ms_send = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ms_msg = new javax.swing.JTextArea();
        ms_back = new javax.swing.JButton();
        ms_Browse = new javax.swing.JButton();
        attach = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ms_label_to.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ms_label_to.setText("To:");

        ms_label_subject.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ms_label_subject.setText("Subject :");

        ms_sendid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ms_sendidActionPerformed(evt);
            }
        });

        ms_subject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ms_subjectActionPerformed(evt);
            }
        });

        ms_send.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        ms_send.setText("SEND");
        ms_send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ms_sendActionPerformed(evt);
            }
        });

        ms_msg.setColumns(20);
        ms_msg.setRows(5);
        jScrollPane1.setViewportView(ms_msg);

        ms_back.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ms_back.setText("BACK");
        ms_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ms_backActionPerformed(evt);
            }
        });

        ms_Browse.setText("Browse");
        ms_Browse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ms_BrowseActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Attachments :");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication6/newpackage/global_logo_.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Send an E-MAIL");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addGap(105, 105, 105)
                                .addComponent(jLabel7))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ms_label_to)
                                    .addComponent(ms_label_subject)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ms_sendid, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ms_subject, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(ms_back, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(ms_send, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(attach, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ms_Browse, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ms_sendid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ms_label_to))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ms_subject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ms_label_subject))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(attach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ms_Browse))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ms_send)
                    .addComponent(ms_back, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ms_sendidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ms_sendidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ms_sendidActionPerformed

    private void ms_subjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ms_subjectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ms_subjectActionPerformed

    private void ms_sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ms_sendActionPerformed
        // TODO add your handling code here:
        
         to = ms_sendid.getText();
        subject = ms_subject.getText();
         msg = ms_msg.getText();
       // File[] attachFiles = null;
        Component frame = null;
        
      
        if("".equals(to))
        {
             JOptionPane.showMessageDialog(frame,"Enter receipient Email");
        }
        else if("".equals(subject))
        {
            JOptionPane.showMessageDialog(frame,"Enter Subject");
        }
        else if("".equals(msg))
        {
           JOptionPane.showMessageDialog(frame,"Blank Message");
        }
        else
        {
          
Properties props = new Properties();
props.put("mail.smtp.host","smtp.gmail.com");
props.put("mail.smtp.socketFactory.port","465");
props.put("mail.smtp.socketFactory.class","javax.net.ssl.SSLSocketFactory");
props.put("mail.smtp.auth","true");
props.put("mail.smtp.port","465");
Session session = Session.getDefaultInstance(props,new javax.mail.Authenticator(){
@Override
public PasswordAuthentication getPasswordAuthentication() {
 return new PasswordAuthentication(userid1,pass1); //CHANGE IT TO YOUR EMAIL ID
            }}
);

try{
Message message = new MimeMessage(session);
message.setFrom(new InternetAddress(userid1));

message.setRecipients(Message.RecipientType.TO,InternetAddress.parse(to));
message.setSubject(subject);

MimeBodyPart mbp = new MimeBodyPart();
mbp.setText(msg);
Multipart mp = new MimeMultipart();
mp.addBodyPart(mbp);

MimeBodyPart mbp1 = new MimeBodyPart();
javax.activation.DataSource ds = new FileDataSource(attachment);

mbp1.setDataHandler(new DataHandler(ds));
mbp1.setFileName("attachment");

mp.addBodyPart(mbp1);


message.setContent(mp);


Transport.send(message);
JOptionPane.showMessageDialog(frame,"Sent");
}
catch(MessagingException | HeadlessException e)
{
JOptionPane.showMessageDialog(frame,e);
}

        }
        
       
    }//GEN-LAST:event_ms_sendActionPerformed

    private void ms_BrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ms_BrowseActionPerformed
        // TODO add your handling code here:
        /*JFileChooser jc = new JFileChooser();
jc.setDialogType(JFileChooser.OPEN_DIALOG);
jc.showOpenDialog(this);
File f= jc.getSelectedFile();
attachment = f.getAbsolutePath();
attach.setText(attachment);*/
        JFileChooser chooser = new JFileChooser();
chooser.showOpenDialog(null);
File f = chooser.getSelectedFile();
attachment  = f.getAbsolutePath();
attach.setText(attachment);

        

    }//GEN-LAST:event_ms_BrowseActionPerformed

    private void ms_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ms_backActionPerformed
        // TODO add your handling code here:
        
         new MainUI(userid1,pass1).setVisible(true);
         setVisible(false);
    }//GEN-LAST:event_ms_backActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mailsend.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mailsend.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mailsend.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mailsend.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                String userid ="antiphishing544@gmail.com";
                String pass ="@ntiPhishing";
                new mailsend(userid,pass).setVisible(true);
            }
        });
    }

    String userid1 ="";
    String pass1 ="";
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField attach;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton ms_Browse;
    private javax.swing.JButton ms_back;
    private javax.swing.JLabel ms_label_subject;
    private javax.swing.JLabel ms_label_to;
    private javax.swing.JTextArea ms_msg;
    private javax.swing.JButton ms_send;
    private javax.swing.JTextField ms_sendid;
    private javax.swing.JTextField ms_subject;
    // End of variables declaration//GEN-END:variables
String to,subject,msg,attachment;
}
