/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication6;

//import net.codejava.swing.mail.SwingEmailSender;

/**
 *
 * @author ypila
 * 
 */
import java.awt.Container;
import java.awt.FlowLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.ScrollPaneConstants;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

public class MainUI extends javax.swing.JFrame   {

    /**
     * Creates new form MainUI
     */
    DefaultTableModel model ;
    public MainUI(String user,String pass) {
        userid2 =user;
        pass2 = pass;
        initComponents();
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jToolBar1 = new javax.swing.JToolBar();
        main_inbox = new javax.swing.JButton();
        main_phishbox = new javax.swing.JButton();
        main_sendmail = new javax.swing.JButton();
        main_logout = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jToolBar1.setRollover(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        main_inbox.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        main_inbox.setText("INBOX");
        main_inbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                main_inboxActionPerformed(evt);
            }
        });
        getContentPane().add(main_inbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 140, 97, -1));

        main_phishbox.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        main_phishbox.setText("PHISHBOX");
        main_phishbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                main_phishboxActionPerformed(evt);
            }
        });
        getContentPane().add(main_phishbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 180, -1, -1));

        main_sendmail.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        main_sendmail.setText("COMPOSE MAIL");
        main_sendmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                main_sendmailActionPerformed(evt);
            }
        });
        getContentPane().add(main_sendmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 220, 137, -1));

        main_logout.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        main_logout.setText("LOGOUT");
        main_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                main_logoutActionPerformed(evt);
            }
        });
        getContentPane().add(main_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 260, 96, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication6/newpackage/global_logo_.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 380));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("MENU");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 50, 90, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication6/newpackage/splash.gif"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void main_sendmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_main_sendmailActionPerformed
        // TODO add your handling code here:
       new mailsend(userid2,pass2).setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_main_sendmailActionPerformed

    private void main_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_main_logoutActionPerformed
        // TODO add your handling code here:
        
        Connection c = null;
        Statement stmt = null;
        String url = "jdbc:mysql://127.0.0.1:3306/";
        String dbName = "antiphishing";
        String driver = "com.mysql.jdbc.Driver";
        String userName = "root";
        String dbpassword = "";
        try {
            Class.forName(driver);
            c = DriverManager.getConnection(url+dbName,userName,dbpassword);
            // Creating statement for the connection to use sql queries
            c.setAutoCommit(false);
            System.out.println("Opened database successfully");

            stmt = c.createStatement();
            String sql = "DELETE FROM MAIL ";// + "WHERE mid = 67";
            stmt.executeUpdate(sql);
            System.out.println("record deleted2");
            String sql1 = "DELETE FROM PHISH";// + "WHERE mid = 67";
            stmt.executeUpdate(sql1);
            System.out.println("record deleted2");
            stmt.close();
            c.commit();
            c.close();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MainUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(MainUI.class.getName()).log(Level.SEVERE, null, ex);
        }
       try {
       
        
      
      
       }
       catch(Exception e)
       {
           
       }
        new Login().setVisible(true);
          setVisible(false);
    }//GEN-LAST:event_main_logoutActionPerformed

    private void main_inboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_main_inboxActionPerformed
        try {
            // TODO add your handling code here:
            int i = 0;
            new NewClass();
        } catch (Exception ex) {
            Logger.getLogger(MainUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }//GEN-LAST:event_main_inboxActionPerformed

    private void main_phishboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_main_phishboxActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            int i = 1;
           new NewClass1();
        } catch (Exception ex) {
            Logger.getLogger(MainUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_main_phishboxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                String userid2 ="";
                String pass2 ="";
                new MainUI(userid2,pass2).setVisible(true);
            }
        });
    }
int selected;
     Connection cn = null;
       Statement stmt = null; 
       ResultSet rs = null;
       String userid2 = "";
       String pass2 ="";
     //JButton jb;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton main_inbox;
    private javax.swing.JButton main_logout;
    private javax.swing.JButton main_phishbox;
    private javax.swing.JButton main_sendmail;
    // End of variables declaration//GEN-END:variables
}
